Entrada

In [221]:
from loaders import Loaders
from utils import Utils
ld= Loaders()
utils= Utils()

In [222]:

# 01 - Cargar y visualizar base (Basenotificar.xlsx)

from loaders import Loaders
ld = Loaders()
path_archivo = r"input/Basenotificar.xlsx"  # <-- cambia si tu ruta es distinta
nombre_hoja = "query"                       # <-- tu hoja se llama "query"
df = ld.cargar_excel(path_archivo, nombre_hoja)

if df is None:
    raise FileNotFoundError(
        "No se pudo cargar el Excel. Revisa:\n"
        f"- Ruta: {path_archivo}\n"
        f"- Hoja: {nombre_hoja}\n"
        "Si el archivo expiró en el chat, vuelve a subirlo o cópialo a ./input/"
    )


print("✅ Base cargada correctamente")
print("Shape (filas, columnas):", df.shape)
print("\nColumnas:")
print(df.columns.tolist())

display(df.head(10))
display(df.info())

# Nulos por columna (top 30 para no saturar)
nulos = df.isna().sum().sort_values(ascending=False)
display(nulos.head(30))

✅ Base cargada correctamente
Shape (filas, columnas): (209, 42)

Columnas:
['Notificador/Revisor', 'numero_expediente', 'Regional', 'Estado de la Actuacion', 'ACTUACION', 'Norma Aplicable', 'Permisivo/Sancionatorio', 'Recurso', 'Acto_Administrativo_No_y_fecha', 'Recurso_actoadministrativo', 'Ordena', 'Tipo de Acto Administrativo', 'Funcionario que expide', 'Nombre Notificado', 'Tipo de documento', 'Numero Documento', 'No. DireccionEfectiva', 'Autoriza Notificacion electrónica', 'Correo Electronico', 'Radicado de autorización Electronica', 'Modo de envío', 'Etiqueta de color', 'Id. de activo de cumplimiento normativo', 'ID', 'Tipo de contenido', 'Modificado', 'Creado', 'Creado por', 'Modificado por', 'Versión', 'Datos adjuntos', 'Editar', 'Tipo', 'Número secundario de elemento', 'Recuento secundario de carpetas', 'Configuración de la etiqueta', 'Etiqueta de retención', 'Etiqueta de retención aplicada', 'Usuario que ha aplicado la etiqueta:', 'El elemento es un registro', 'Aplicación creada por', 'Aplicación modificada por']

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Tipo,Número secundario de elemento,Recuento secundario de carpetas,Configuración de la etiqueta,Etiqueta de retención,Etiqueta de retención aplicada,Usuario que ha aplicado la etiqueta:,El elemento es un registro,Aplicación creada por,Aplicación modificada por
0,Ana Maria Guzman Acosta,39618,Bajo Magdalena,Enviado,EN OTRO ESTADO SAE,Ley 1437,Sancionatorio,Recurso,Resolucion DJA No. 50257000923 del 29 Octubr...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
1,Ana Maria Guzman Acosta,39618,Bajo Magdalena,Enviado,EN OTRO ESTADO SAE,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN No. 50257000923 del 29 de octubre ...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
2,Ana Maria Guzman Acosta,39618,Bajo Magdalena,Enviado,EN OTRO ESTADO SAE,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN No. 50257000923 del 29 de octubre ...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
3,Ana Maria Guzman Acosta,41735,Bajo Magdalena,En consulta de la Regional,EN CONSULTA DR,Ley 1437,Sancionatorio,Recurso,Resolución N°4705 Del 31 de Diciembre de 2018,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
4,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
5,Andrea Claudia Martin Martinez,81918,Soacha,Enviado,NOTIFICACIÓN ELECTRÓNICA,Ley 1437,Sancionatorio,No recurso,Resolución DJA No. 50267000060 del 17 de febre...,No Aplica,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
6,Andrea Claudia Martin Martinez,73233,Soacha,Enviado,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DJUR No. 50257000727 del 23 de sept...,No aplica,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
7,Andrea Claudia Martin Martinez,93441,Soacha,Enviado,COMUNICACION,Ley 1437,Permisivo,Recurso,Resolución DRSOA No. 11257000090 del 02 de dic...,Reposición,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
8,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Enviado,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,NaN,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
9,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Enviado,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform

<class 'pandas.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 42 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Notificador/Revisor                      209 non-null    str
 1   numero_expediente                        209 non-null    int64
 2   Regional                                 209 non-null    str
 3   Estado de la Actuacion                   209 non-null    str
 4   ACTUACION                                209 non-null    str
 5   Norma Aplicable                          209 non-null    str
 6   Permisivo/Sancionatorio                  209 non-null    str
 7   Recurso                                  209 non-null    str
 8   Acto_Administrativo_No_y_fecha           209 non-null    str
 9   Recurso_actoadministrativo               193 non-null    str
 10  Ordena                                   209 non-null    str
 11  Tipo de Acto Administrativo              209 non-null    str
 12  Funcionario que expide                   209 non-null    str
 13  Nombre Notificado                        209 non-null    str
 14  Tipo de documento                        209 non-null    str
 15  Numero Documento                         207 non-null    str
 16  No. DireccionEfectiva                    206 non-null    str
 17  Autoriza Notificacion electrónica        209 non-null    bool
 18  Correo Electronico                       118 non-null    str
 19  Radicado de autorización Electronica     45 non-null     float64
 20  Modo de envío                            209 non-null    str
 21  Etiqueta de color                        0 non-null      float64
 22  Id. de activo de cumplimiento normativo  0 non-null      float64
 23  ID                                       209 non-null    int64
 24  Tipo de contenido                        209 non-null    str
 25  Modificado                               209 non-null    datetime64[us]
 26  Creado                                   209 non-null    datetime64[us]
 27  Creado por                               209 non-null    str
 28  Modificado por                           209 non-null    str
 29  Versión                                  209 non-null    float64
 30  Datos adjuntos                           209 non-null    int64
 31  Editar                                   0 non-null      float64
 32  Tipo                                     0 non-null      float64
 33  Número secundario de elemento            209 non-null    int64
 34  Recuento secundario de carpetas          209 non-null    int64
 35  Configuración de la etiqueta             0 non-null      float64
 36  Etiqueta de retención                    0 non-null      float64
 37  Etiqueta de retención aplicada           0 non-null      float64
 38  Usuario que ha aplicado la etiqueta:     0 non-null      float64
 39  El elemento es un registro               0 non-null      float64
 40  Aplicación creada por                    209 non-null    str
 41  Aplicación modificada por                209 non-null    str
dtypes: bool(1), datetime64[us](2), float64(11), int64(5), str(23)
memory usage: 67.3 KB

None

Etiqueta de color                          209
Configuración de la etiqueta               209
Tipo                                       209
Editar                                     209
Etiqueta de retención                      209
El elemento es un registro                 209
Usuario que ha aplicado la etiqueta:       209
Etiqueta de retención aplicada             209
Id. de activo de cumplimiento normativo    209
Radicado de autorización Electronica       164
Correo Electronico                          91
Recurso_actoadministrativo                  16
No. DireccionEfectiva                        3
Numero Documento                             2
Acto_Administrativo_No_y_fecha               0
ACTUACION                                    0
Regional                                     0
numero_expediente                            0
Notificador/Revisor                          0
Recurso                                      0
Permisivo/Sancionatorio                      0
Norma Aplicable                              0
Estado de la Actuacion                       0
Autoriza Notificacion electrónica            0
Ordena                                       0
Tipo de Acto Administrativo                  0
Modificado                                   0
Tipo de contenido                            0
ID                                           0
Modo de envío                                0
dtype: int64

Segmentos de elaborar oficios

In [223]:
# ============================================================
# 02 - Filtrar SOLO los registros con "Elaborar Oficio"
#      (columna correcta: "Estado de la Actuacion")
# ============================================================

import unicodedata

def _norm_txt(x: str) -> str:
    x = "" if x is None else str(x)
    x = x.strip().upper()
    x = " ".join(x.split())
    x = unicodedata.normalize("NFKD", x).encode("ascii", "ignore").decode("ascii")
    return x

col_estado_act = "Estado de la Actuacion"
valor_objetivo = "Elaborar Oficio"


if col_estado_act not in df.columns:
    # Si por algún motivo viene con otra escritura, mostramos candidatas
    candidatas = [c for c in df.columns if "estado" in _norm_txt(c) and "actu" in _norm_txt(c)]
    raise KeyError(
        f"No existe la columna '{col_estado_act}'.\n"
        f"Candidatas encontradas: {candidatas}\n"
        f"Columnas disponibles: {df.columns.tolist()}"
    )

tmp = df.copy()
tmp["_estado_norm"] = tmp[col_estado_act].map(_norm_txt)

df_filtrado = tmp[tmp["_estado_norm"] == _norm_txt(valor_objetivo)].drop(columns=["_estado_norm"]).copy()
df_filtrado.reset_index(drop=True, inplace=True)

print("✅ Filtrado aplicado por Estado de la Actuacion == 'Elaborar Oficio'")
print("Shape original:", df.shape)
print("Shape filtrado :", df_filtrado.shape)

display(df_filtrado.head(10))
display(df[col_estado_act].astype(str).value_counts(dropna=False).head(20))

✅ Filtrado aplicado por Estado de la Actuacion == 'Elaborar Oficio'
Shape original: (209, 42)
Shape filtrado : (180, 42)

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Tipo,Número secundario de elemento,Recuento secundario de carpetas,Configuración de la etiqueta,Etiqueta de retención,Etiqueta de retención aplicada,Usuario que ha aplicado la etiqueta:,El elemento es un registro,Aplicación creada por,Aplicación modificada por
0,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
1,Ana Maria Guzman Acosta,45586,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución No. 1387 de 31 de mayo de 2017,Reposición,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
2,Laura Stephania Martinez Leandro,44696,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000463 del 11 de juli...,Recurso de reposición,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
3,Laura Stephania Martinez Leandro,53016,Alto Magdalena,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000556 del 21 de agos...,recurso de reposición,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
4,Laura Stephania Martinez Leandro,57314,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DRAM No. 03257000146 del 24 de sept...,recurso de reposición,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
5,Laura Stephania Martinez Leandro,74305,Alto Magdalena,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJA No. 50257001140 del 24 de dicie...,recurso de reposición,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
6,Diana Carolina Morera Acuña,40388,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolución DRBC No. 01237000081 de 31 marzo...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
7,Diana Carolina Morera Acuña,40388,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolucion DRBC No. 01237000081 de 31 marzo...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
8,Diana Carolina Morera Acuña,40388,Bogota la Calera,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolucion DRBC No. 01237000081 de 31 marzo...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform
9,Diana Carolina Morera Acuña,41480,Bogota la Calera,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50237000469 de 31 MAR. ...,Reposicion,...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform

Estado de la Actuacion
Elaborar Oficio               180
Enviado                        23
En consulta de la Regional      6
Name: count, dtype: int64

Agregamos Regionales con nombre de director e indicador

In [224]:


df_filtrado = utils.agregar_info_regional(df_filtrado, col_regional="Regional")

print("✅ Columnas agregadas:", ["INDICADOR", "DIRECTOR_REGIONAL"])
display(df_filtrado[["Regional", "INDICADOR", "DIRECTOR_REGIONAL"]].head(15))

✅ Columnas agregadas: ['INDICADOR', 'DIRECTOR_REGIONAL']

            Regional INDICADOR                DIRECTOR_REGIONAL
0   Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
1     Bajo Magdalena      DRBM   JUAN FILIBERTO COTRINO GUEVARA
2     Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
3     Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
4     Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
5     Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
6   Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
7   Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
8   Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
9   Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
10  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
11  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
12  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
13  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
14  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO

In [225]:
df_filtrado

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Etiqueta de retención,Etiqueta de retención aplicada,Usuario que ha aplicado la etiqueta:,El elemento es un registro,Aplicación creada por,Aplicación modificada por,INDICADOR,DIRECTOR_REGIONAL,DIRECCION_REGIONAL,MUNICIPIO_REGIONAL
0,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
1,Ana Maria Guzman Acosta,45586,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución No. 1387 de 31 de mayo de 2017,Reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
2,Laura Stephania Martinez Leandro,44696,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000463 del 11 de juli...,Recurso de reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
3,Laura Stephania Martinez Leandro,53016,Alto Magdalena,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000556 del 21 de agos...,recurso de reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
4,Laura Stephania Martinez Leandro,57314,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DRAM No. 03257000146 del 24 de sept...,recurso de reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Laura Stephania Martinez Leandro,66501,Ubate,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000835 del 21 OCT. 2025,En contra de la presente resolución procede ún...,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRUB,JULIO CESAR SIERRA LEON,Transversal 2da. N°1E-40,"Ubaté, Cundinamarca"
176,Laura Stephania Martinez Leandro,66501,Ubate,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000835 de 21 OCT. 2025,En contra de la presente resolución procede ún...,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRUB,JULIO CESAR SIERRA LEON,Transversal 2da. N°1E-40,"Ubaté, Cundinamarca"
177,Laura Stephania Martinez Leandro,66501,Ubate,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000835 de 21 OCT. ...,En contra de la presente resolución procede ú...,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRUB,JULIO CESAR SIERRA LEON,Transversal 2da. N°1E-40,"Ubaté, Cundinamarca"
178,Laura Stephania Martinez Leandro,66501,Ubate,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000835 de 21 OCT. ...,En contra de la presente resolución procede ún...,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRUB,JULIO CESAR SIERRA LEON,Transversal 2da. N°1E-40,"Ubaté, Cundinamarca"
179,Julian David Robles Farias,1111111,Rionegro,Elaborar Oficio,AVISO,Decreto 01,Sancionatorio,No recurso,111111 2001/12/15,NaN,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRRN,ALEJANDRO FUQUITVA CASALLAS,"Calle 9 N° 19-72, Barrio Antonio Nariño","Pacho, Cundinamarca"

Direcciones de cada regional

In [226]:


df_filtrado = utils.agregar_info_regional(df_filtrado, col_regional="Regional")

display(
    df_filtrado[["Regional", "INDICADOR", "DIRECTOR_REGIONAL", "DIRECCION_REGIONAL", "MUNICIPIO_REGIONAL"]]
    .head(15)
)

,Regional,INDICADOR,DIRECTOR_REGIONAL,DIRECCION_REGIONAL,MUNICIPIO_REGIONAL
0,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
1,Bajo Magdalena,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
2,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
3,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
4,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
5,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
6,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
7,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
8,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
9,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
10,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
11,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
12,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
13,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
14,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"

Validacion de dataframe en asignaciones

In [227]:
print("📌 RESUMEN GENERAL")
print("="*50)
print("Filas:", df_filtrado.shape[0])
print("Columnas:", df_filtrado.shape[1])
print("="*50)

display(df_filtrado.head(5))

📌 RESUMEN GENERAL
==================================================
Filas: 180
Columnas: 46
==================================================

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Etiqueta de retención,Etiqueta de retención aplicada,Usuario que ha aplicado la etiqueta:,El elemento es un registro,Aplicación creada por,Aplicación modificada por,INDICADOR,DIRECTOR_REGIONAL,DIRECCION_REGIONAL,MUNICIPIO_REGIONAL
0,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
1,Ana Maria Guzman Acosta,45586,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución No. 1387 de 31 de mayo de 2017,Reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
2,Laura Stephania Martinez Leandro,44696,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000463 del 11 de juli...,Recurso de reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
3,Laura Stephania Martinez Leandro,53016,Alto Magdalena,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000556 del 21 de agos...,recurso de reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
4,Laura Stephania Martinez Leandro,57314,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DRAM No. 03257000146 del 24 de sept...,recurso de reposición,...,NaN,NaN,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"

DataFrame con abogados independientes

In [228]:
import importlib
import utils as utils_module
importlib.reload(utils_module)

from utils import Utils
utils = Utils()

print("✅ utils recargado. Métodos disponibles (filtrado):")
print([m for m in dir(utils) if "persona" in m or "cruce" in m])

✅ utils recargado. Métodos disponibles (filtrado):
['agregar_fila_cruce', 'agregar_fila_cruce_excel', 'agregar_fila_cruce_word', 'exportar_excels_por_persona', 'partir_por_persona_con_cruce']

complemento textual

In [229]:
col_origen = "Tipo de Acto Administrativo"

df_filtrado = utils.agregar_columnas_del_de_la(
    df_filtrado,
    col_origen=col_origen,
    col_articulo="articulo_preposicion",
    col_frase="descripcion_con_articulo",
    minusculas=True
)

df_filtrado[[col_origen, "articulo_preposicion", "descripcion_con_articulo"]].head(20)

   Tipo de Acto Administrativo articulo_preposicion descripcion_con_articulo
0                   Resolución                de la         de la resolución
1                   Resolución                de la         de la resolución
2                   Resolución                de la         de la resolución
3                   Resolución                de la         de la resolución
4                   Resolución                de la         de la resolución
5                   Resolución                de la         de la resolución
6                   Resolución                de la         de la resolución
7                   Resolución                de la         de la resolución
8                   Resolución                de la         de la resolución
9                   Resolución                de la         de la resolución
10                  Resolución                de la         de la resolución
11                  Resolución                de la         de la resolución
12                  Resolución                de la         de la resolución
13                  Resolución                de la         de la resolución
14                  Resolución                de la         de la resolución
15                  Resolución                de la         de la resolución
16                  Resolución                de la         de la resolución
17                  Resolución                de la         de la resolución
18                  Resolución                de la         de la resolución
19                  Resolución                de la         de la resolución

Exportar excel abogado

In [230]:
resumen = utils.exportar_excels_por_persona(
    df=df_filtrado,
    col_persona="Notificador/Revisor",
    carpeta_salida="output_abogados",
    nombre_prefix="OFICIOS",
    add_fila_cruce=True,
    col_fila_cruce="No_Fila_Cruce",
    offset_fila_cruce=1
)

display(resumen)

,persona,filas,ruta_archivo
0,Ana Maria Guzman Acosta,65,output_abogados\OFICIOS_Ana_Maria_Guzman_Acost...
1,Andrea Claudia Martin Martinez,6,output_abogados\OFICIOS_Andrea_Claudia_Martin_...
2,Diana Carolina Morera Acuña,49,output_abogados\OFICIOS_Diana_Carolina_Morera_...
3,Julian David Robles Farias,1,output_abogados\OFICIOS_Julian_David_Robles_Fa...
4,Laura Stephania Martinez Leandro,19,output_abogados\OFICIOS_Laura_Stephania_Martin...
5,Valentina Bernal Triana,40,output_abogados\OFICIOS_Valentina_Bernal_Trian...

# FASE 2. CREACION DE OFICIOS

In [231]:
resumen = utils.exportar_excels_por_persona(
    df=df_filtrado,
    col_persona="Notificador/Revisor",
    carpeta_salida="output_abogados",
    nombre_prefix="OFICIOS",
    add_fila_cruce=True,
    col_fila_cruce="No_Fila_Cruce",
    offset_fila_cruce=1
)
display(resumen)

,persona,filas,ruta_archivo
0,Ana Maria Guzman Acosta,65,output_abogados\OFICIOS_Ana_Maria_Guzman_Acost...
1,Andrea Claudia Martin Martinez,6,output_abogados\OFICIOS_Andrea_Claudia_Martin_...
2,Diana Carolina Morera Acuña,49,output_abogados\OFICIOS_Diana_Carolina_Morera_...
3,Julian David Robles Farias,1,output_abogados\OFICIOS_Julian_David_Robles_Fa...
4,Laura Stephania Martinez Leandro,19,output_abogados\OFICIOS_Laura_Stephania_Martin...
5,Valentina Bernal Triana,40,output_abogados\OFICIOS_Valentina_Bernal_Trian...

In [232]:
resumen = utils.exportar_excels_por_persona(
    df=df_filtrado,
    col_persona="Notificador/Revisor",
    carpeta_salida="output_abogados",
    nombre_prefix="OFICIOS",
    add_fila_cruce=True,
    col_fila_cruce="No_Fila_Cruce",
    offset_fila_cruce=1
)
display(resumen)

,persona,filas,ruta_archivo
0,Ana Maria Guzman Acosta,65,output_abogados\OFICIOS_Ana_Maria_Guzman_Acost...
1,Andrea Claudia Martin Martinez,6,output_abogados\OFICIOS_Andrea_Claudia_Martin_...
2,Diana Carolina Morera Acuña,49,output_abogados\OFICIOS_Diana_Carolina_Morera_...
3,Julian David Robles Farias,1,output_abogados\OFICIOS_Julian_David_Robles_Fa...
4,Laura Stephania Martinez Leandro,19,output_abogados\OFICIOS_Laura_Stephania_Martin...
5,Valentina Bernal Triana,40,output_abogados\OFICIOS_Valentina_Bernal_Trian...

In [233]:
df_filtrado = utils.agregar_info_regional(df_filtrado, col_regional="Regional")
df_filtrado = utils.agregar_columnas_del_de_la(df_filtrado, col_origen="Tipo de Acto Administrativo")

EXCEL OPERATIVO GENERAL DE OFICIOS

In [234]:
def buscar_col(df, posibles):
    def norm(s):
        return str(s).strip().lower().replace(" ", "").replace("_", "").replace(".", "")
    cols = list(df.columns)
    cols_norm = {norm(c): c for c in cols}
    for p in posibles:
        if norm(p) in cols_norm:
            return cols_norm[norm(p)]
    for p in posibles:
        for c in cols:
            if norm(p) in norm(c):
                return c
    return None

col_notificador = buscar_col(df_filtrado, ["Notificador/Revisor", "Notificador"])
col_estado      = buscar_col(df_filtrado, ["Estado_Actuacion", "Estado Actuacion", "Estado Actuación", "Estado"])
col_tipo_oficio = buscar_col(df_filtrado, ["Tipo_Oficio", "Tipo de Acto Administrativo", "Tipo Oficio"])
col_expediente  = buscar_col(df_filtrado, ["numero_expediente", "No. Exp.", "Expediente"])
col_notificado  = buscar_col(df_filtrado, ["Nombre_Notificado", "Nombre Notificado", "Notificado"])

print("Detectadas:")
print("col_notificador:", col_notificador)
print("col_estado:", col_estado)
print("col_tipo_oficio:", col_tipo_oficio)
print("col_expediente:", col_expediente)
print("col_notificado:", col_notificado)

Detectadas:
col_notificador: Notificador/Revisor
col_estado: Estado de la Actuacion
col_tipo_oficio: Tipo de Acto Administrativo
col_expediente: numero_expediente
col_notificado: Nombre Notificado

In [235]:
res_operativo = utils.exportar_excel_oficios_y_ejecutorias_por_notificador(
    df=df_filtrado,
    col_notificador=col_notificador,
    col_estado_actuacion=col_estado,
    col_tipo_oficio=col_tipo_oficio,
    col_expediente=col_expediente,
    col_notificado=col_notificado,
    carpeta_salida="output_abogados",
    nombre_archivo="RESUMEN_OFICIOS_Y_EJECUTORIAS.xlsx",
)

display(res_operativo)

,abogado,oficios_por_crear,ejecutorias,ruta_excel
0,Ana Maria Guzman Acosta,65,0,output_abogados\Ana_Maria_Guzman_Acosta\RESUME...
1,Andrea Claudia Martin Martinez,6,0,output_abogados\Andrea_Claudia_Martin_Martinez...
2,Diana Carolina Morera Acuña,49,0,output_abogados\Diana_Carolina_Morera_Acuña\RE...
3,Julian David Robles Farias,1,0,output_abogados\Julian_David_Robles_Farias\RES...
4,Laura Stephania Martinez Leandro,19,0,output_abogados\Laura_Stephania_Martinez_Leand...
5,Valentina Bernal Triana,40,0,output_abogados\Valentina_Bernal_Triana\RESUME...

EJECUTAR WORD

In [236]:
# ¿Qué métodos tiene tu objeto utils?
[m for m in dir(utils) if "plantilla" in m.lower() or "word" in m.lower()]

['_mapa_plantillas_docx',
 '_obtener_ruta_plantilla_por_tipo',
 '_ruta_plantillas',
 'agregar_fila_cruce_word',
 'generar_words_desde_plantilla',
 'generar_words_desde_tipo_oficio']

In [237]:
import importlib
import utils as utils_module

importlib.reload(utils_module)

utils = utils_module.Utils()

print("¿Existe generar_words_desde_plantilla?:",
      hasattr(utils, "generar_words_desde_plantilla"))

¿Existe generar_words_desde_plantilla?: True

In [238]:
import os
import sys
import pandas as pd

print("Python del notebook:", sys.executable)

# 0) Validación: df_filtrado existe
if "df_filtrado" not in globals():
    raise NameError("df_filtrado NO existe. Ejecuta primero la parte donde cargas/creas df_filtrado.")

print("✅ df_filtrado OK. Filas:", len(df_filtrado), "Columnas:", len(df_filtrado.columns))
display(df_filtrado.head(3))

Python del notebook: c:\Users\JULIANCHO ROBLES\Desktop\PROYECTOS GITHUB\oficios_notificaciones\venv\Scripts\python.exe
✅ df_filtrado OK. Filas: 180 Columnas: 48

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Usuario que ha aplicado la etiqueta:,El elemento es un registro,Aplicación creada por,Aplicación modificada por,INDICADOR,DIRECTOR_REGIONAL,DIRECCION_REGIONAL,MUNICIPIO_REGIONAL,articulo_preposicion,descripcion_con_articulo
0,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca",de la,de la resolución
1,Ana Maria Guzman Acosta,45586,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución No. 1387 de 31 de mayo de 2017,Reposición,...,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca",de la,de la resolución
2,Laura Stephania Martinez Leandro,44696,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000463 del 11 de juli...,Recurso de reposición,...,NaN,NaN,Microsoft Power Platform,Microsoft Power Platform,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca",de la,de la resolución

crear oficios

In [239]:
COL_ESTADO = "Estado de la Actuacion"   # <- tu nombre real
COL_ACTUACION = "ACTUACION"            # <- tu nombre real

# 1) Filtrar SOLO elaborar oficio
df_oficios = df_filtrado.copy()

df_oficios = df_oficios[
    df_oficios[COL_ESTADO].astype(str).str.strip().str.lower().eq("elaborar oficio")
].copy()

# 2) Excluir ejecutorias por texto en ACTUACION (si aplica)
df_oficios = df_oficios[
    ~df_oficios[COL_ACTUACION].astype(str).str.upper().str.contains("EJECUTORIA", na=False)
].copy()

print("✅ Filas para Word (oficios sin ejecutorias):", len(df_oficios))
display(df_oficios[[COL_ESTADO, COL_ACTUACION, "numero_expediente", "Nombre Notificado", "Notificador/Revisor"]].head(10))

✅ Filas para Word (oficios sin ejecutorias): 127

,Estado de la Actuacion,ACTUACION,numero_expediente,Nombre Notificado,Notificador/Revisor
0,Elaborar Oficio,COMUNICACION,40381,"PROCURADURIA 22 JUDICIAL II, AMBIENTAL Y AGRARIA""",Diana Carolina Morera Acuña
3,Elaborar Oficio,PUBLICAR AVISO,53016,MARTHA DE LA CONCEPCION GOMEZ CASTRO,Laura Stephania Martinez Leandro
5,Elaborar Oficio,PUBLICAR AVISO,74305,FERNANDO REY MORENO,Laura Stephania Martinez Leandro
6,Elaborar Oficio,CITACION,40388,HECTOR JAIRO SARMIENTO GOMEZ,Diana Carolina Morera Acuña
7,Elaborar Oficio,CITACION,40388,GABRIEL ESTRADA,Diana Carolina Morera Acuña
8,Elaborar Oficio,AVISO,40388,ESTRAURI S.A.S,Diana Carolina Morera Acuña
9,Elaborar Oficio,AVISO,41480,ANDRES BARRAGAN TOBAR,Diana Carolina Morera Acuña
10,Elaborar Oficio,COMUNICACION,41480,PROCURADORIA JUDICIAL AMBIENTAL Y AGRARIA,Diana Carolina Morera Acuña
11,Elaborar Oficio,CITACION,41564,RAUL CASTELLANOS,Diana Carolina Morera Acuña
12,Elaborar Oficio,CITACION,41564,CARLOS MUÑOZ ROJAS,Diana Carolina Morera Acuña

In [240]:
# NORMALIZAR COLUMNAS PARA PLANTILLA WORD


df_oficios = df_oficios.copy()

alias_cols = {
    "Numero Documento": "Numero_Documento",
    "Correo Electronico": "Correo_Electronico",
    "No. DireccionEfectiva": "No_DireccionEfectiva",
    "Modo de envío": "Modo_de_envío",
}

faltan_origen = [c for c in alias_cols.keys() if c not in df_oficios.columns]
if faltan_origen:
    print("❌ Faltan estas columnas ORIGEN en df_oficios (revisa el nombre exacto):")
    for c in faltan_origen:
        print("   -", repr(c))
else:
    for origen, destino in alias_cols.items():
        df_oficios[destino] = df_oficios[origen]

    print("✅ Columnas creadas para plantilla:")
    for _, destino in alias_cols.items():
        print("   -", destino)

# (Opcional pero recomendado) Verifica rápido que ya existen:
check = ["Numero_Documento", "Correo_Electronico", "No_DireccionEfectiva", "Modo_de_envío"]
print("\n🔎 Verificación:")
for c in check:
    print(c, "->", "OK" if c in df_oficios.columns else "❌ NO")

✅ Columnas creadas para plantilla:
   - Numero_Documento
   - Correo_Electronico
   - No_DireccionEfectiva
   - Modo_de_envío

🔎 Verificación:
Numero_Documento -> OK
Correo_Electronico -> OK
No_DireccionEfectiva -> OK
Modo_de_envío -> OK

In [241]:
import importlib
import utils as utils_mod

importlib.reload(utils_mod)
utils = utils_mod.Utils()  # o como estés instanciando tu clase
print("Existe generar_words_desde_plantilla?", hasattr(utils, "generar_words_desde_plantilla"))

Existe generar_words_desde_plantilla? True

In [242]:
def generar_words_desde_plantilla(
    self,
    df,
    plantilla_path,
    carpeta_salida="output_abogados",
    col_notificador="Notificador/Revisor",
    col_subcarpeta=None,                 # ej: "ACTUACION"
    nombre_archivo_cols=None,            # ej: ["numero_expediente", "Nombre Notificado"]
    col_map=None,                        # {"Numero_Documento": "Numero Documento", ...}
    abrir_cierre="«»",                   # delimitadores de tu plantilla
    max_nombre=140
):
    import os
    import re
    import pandas as pd

    try:
        from docx import Document
    except Exception as e:
        raise ImportError(
            "No se pudo importar python-docx. Instala con: pip install python-docx"
        ) from e

    if df is None or len(df) == 0:
        return pd.DataFrame(columns=["fila", "ruta_docx"])

    if not os.path.exists(plantilla_path):
        raise FileNotFoundError(f"No existe la plantilla en: {plantilla_path}")

    col_map = col_map or {}
    nombre_archivo_cols = nombre_archivo_cols or []

    def _safe_txt(x):
        if x is None:
            return ""
        if isinstance(x, float) and pd.isna(x):
            return ""
        if pd.isna(x):
            return ""
        return str(x)

    def _sanitize(s):
        s = _safe_txt(s).strip()
        s = re.sub(r"[\\/:*?\"<>|]+", "_", s)
        s = re.sub(r"\s+", " ", s).strip()
        if len(s) > max_nombre:
            s = s[:max_nombre].strip()
        return s or "SIN_DATO"

    # Reemplazo simple (si el token está partido entre runs, puede perder formato).
    # Funciona bien si tus «campos» están escritos como texto normal.
    def _replace_in_paragraph(paragraph, replacements):
        text = paragraph.text
        changed = False
        for k, v in replacements.items():
            if k in text:
                text = text.replace(k, v)
                changed = True
        if changed:
            paragraph.text = text

    def _replace_in_table(table, replacements):
        for row in table.rows:
            for cell in row.cells:
                for p in cell.paragraphs:
                    _replace_in_paragraph(p, replacements)
                for t in cell.tables:
                    _replace_in_table(t, replacements)

    izq, der = abrir_cierre[0], abrir_cierre[-1]  # « »
    generados = []

    for i, row in df.reset_index(drop=True).iterrows():

        notificador = _sanitize(row.get(col_notificador, "SIN_NOTIFICADOR"))
        subcarp = _sanitize(row.get(col_subcarpeta, "")) if col_subcarpeta else ""

        # Carpeta final:
        # carpeta_salida/<NOTIFICADOR>/<SUBCARPETA>/WORDS/
        ruta_dir = os.path.join(carpeta_salida, notificador)
        if subcarp:
            ruta_dir = os.path.join(ruta_dir, subcarp)
        ruta_dir = os.path.join(ruta_dir, "WORDS")
        os.makedirs(ruta_dir, exist_ok=True)

        # Nombre del archivo
        partes = []
        for c in nombre_archivo_cols:
            partes.append(_sanitize(row.get(c, "")))
        base_name = "_".join([p for p in partes if p and p != "SIN_DATO"]) or f"doc_{i+1}"
        nombre_doc = f"{base_name}.docx"
        ruta_out = os.path.join(ruta_dir, nombre_doc)

        # Construir replacements desde la fila
        replacements = {}

        # 1) Todos los campos directos que existan en el DF:
        for col in df.columns:
            key = f"{izq}{col}{der}"     # «Nombre Notificado»
            replacements[key] = _safe_txt(row.get(col, ""))

        # 2) Map de plantilla->col real (para casos como Numero_Documento vs Numero Documento)
        for campo_plantilla, col_real in col_map.items():
            key = f"{izq}{campo_plantilla}{der}"  # «Numero_Documento»
            replacements[key] = _safe_txt(row.get(col_real, ""))

        # Cargar plantilla y reemplazar
        doc = Document(plantilla_path)

        for p in doc.paragraphs:
            _replace_in_paragraph(p, replacements)

        for t in doc.tables:
            _replace_in_table(t, replacements)

        doc.save(ruta_out)
        generados.append({"fila": i, "ruta_docx": ruta_out})

    return pd.DataFrame(generados)

In [243]:
import os
import pandas as pd
import importlib
import utils as utils_mod

# 1) Recargar utils.py (para que agarre el método nuevo)
importlib.reload(utils_mod)
utils = utils_mod.Utils()  # ajusta si tu clase se instancia diferente

# 2) Verifica que ya existe df_filtrado
print("Existe df_filtrado?", "df_filtrado" in globals())
print("Existe metodo generar_words_desde_plantilla?", hasattr(utils, "generar_words_desde_plantilla"))

# 3) Ruta real de plantilla
PLANTILLA = r"plantillas\NOTIFICACION_POR_AVISO.docx"
print("Existe plantilla?", os.path.exists(PLANTILLA), "->", PLANTILLA)

# 4) Filtrar SOLO Elaborar Oficio (según tu columna REAL)
# Tus columnas reales: "Estado de la Actuacion" y "ACTUACION"
df_oficios = df_filtrado.copy()

df_oficios = df_oficios[
    df_oficios["Estado de la Actuacion"].astype(str).str.strip().str.lower().eq("elaborar oficio")
].copy()

# Excluir ejecutorias (si en ACTUACION aparece EJECUTORIA)
df_oficios = df_oficios[
    ~df_oficios["ACTUACION"].astype(str).str.upper().str.contains("EJECUTORIA", na=False)
].copy()

print("✅ Filas a generar (oficios sin ejecutorias):", len(df_oficios))

Existe df_filtrado? True
Existe metodo generar_words_desde_plantilla? True
Existe plantilla? False -> plantillas\NOTIFICACION_POR_AVISO.docx
✅ Filas a generar (oficios sin ejecutorias): 127

In [244]:
print("Existe df_filtrado?", "df_filtrado" in globals())
if "df_filtrado" in globals():
    print("Filas:", len(df_filtrado))
    print("Columnas:", len(df_filtrado.columns))

Existe df_filtrado? True
Filas: 180
Columnas: 48

# Seccion de plantilla para generar words

In [245]:
from utils import Utils

utils = Utils()

cols = {
    "col_notificador": "Notificador/Revisor",
    "col_estado": "Estado de la Actuacion",
    "col_tipo_oficio": "ACTUACION",
    "col_expediente": "numero_expediente",
    "col_notificado": "Nombre Notificado",
}

display(cols)

{'col_notificador': 'Notificador/Revisor',
 'col_estado': 'Estado de la Actuacion',
 'col_tipo_oficio': 'ACTUACION',
 'col_expediente': 'numero_expediente',
 'col_notificado': 'Nombre Notificado'}

In [246]:
print("COLUMNAS REALES DEL DATAFRAME\n")

for c in df_filtrado.columns:
    print(c)

COLUMNAS REALES DEL DATAFRAME

Notificador/Revisor
numero_expediente
Regional
Estado de la Actuacion
ACTUACION
Norma Aplicable
Permisivo/Sancionatorio
Recurso
Acto_Administrativo_No_y_fecha
Recurso_actoadministrativo
Ordena
Tipo de Acto Administrativo
Funcionario que expide
Nombre Notificado
Tipo de documento
Numero Documento
No. DireccionEfectiva
Autoriza Notificacion electrónica
Correo Electronico
Radicado de autorización Electronica
Modo de envío
Etiqueta de color
Id. de activo de cumplimiento normativo
ID
Tipo de contenido
Modificado
Creado
Creado por
Modificado por
Versión
Datos adjuntos
Editar
Tipo
Número secundario de elemento
Recuento secundario de carpetas
Configuración de la etiqueta
Etiqueta de retención
Etiqueta de retención aplicada
Usuario que ha aplicado la etiqueta:
El elemento es un registro
Aplicación creada por
Aplicación modificada por
INDICADOR
DIRECTOR_REGIONAL
DIRECCION_REGIONAL
MUNICIPIO_REGIONAL
articulo_preposicion
descripcion_con_articulo

In [247]:
df_words = df_filtrado.copy()

# 1) Agregar info regional faltante para que existan:
#    INDICADOR, DIRECTOR_REGIONAL, DIRECCION_REGIONAL, MUNICIPIO_REGIONAL
df_words = utils.agregar_info_regional(df_words, col_regional="Regional")

# 2) Crear columnas espejo con los nombres exactos que esperan las plantillas Word
df_words["Numero_Documento"] = df_words["Numero Documento"]
df_words["Correo_Electronico"] = df_words["Correo Electronico"]
df_words["No_DireccionEfectiva"] = df_words["No. DireccionEfectiva"]
df_words["Tipo_de_documento"] = df_words["Tipo de documento"]
df_words["Funcionario_que_expide"] = df_words["Funcionario que expide"]
df_words["Nombre_Notificado"] = df_words["Nombre Notificado"]

# 3) Crear modo de envío
#    Regla inicial:
#    - si autoriza notificación electrónica y hay correo -> ELECTRÓNICO
#    - de lo contrario -> FÍSICO
def construir_modo_envio(row):
    autoriza = str(row.get("Autoriza Notificacion electrónica", "")).strip().lower()
    correo = str(row.get("Correo Electronico", "")).strip()

    if autoriza in ["si", "sí", "s", "true", "1", "x"] and correo != "":
        return "ELECTRÓNICO"
    return "FÍSICO"

df_words["Modo_de_envío"] = df_words.apply(construir_modo_envio, axis=1)
df_words["Modo_de_envio"] = df_words["Modo_de_envío"]

print("Filas base words:", len(df_words))
print("Columnas base words:", len(df_words.columns))

columnas_clave = [
    "Numero_Documento",
    "Correo_Electronico",
    "No_DireccionEfectiva",
    "Regional",
    "INDICADOR",
    "DIRECTOR_REGIONAL",
    "Modo_de_envío",
    "numero_expediente",
    "Acto_Administrativo_No_y_fecha",
    "Nombre_Notificado",
    "Tipo_de_documento",
    "Funcionario_que_expide",
    "Recurso_actoadministrativo",
]

print("\nVALIDACIÓN DE COLUMNAS CLAVE:")
for c in columnas_clave:
    print(c, "->", c in df_words.columns)

display(df_words[columnas_clave].head(3))

Filas base words: 180
Columnas base words: 56

VALIDACIÓN DE COLUMNAS CLAVE:
Numero_Documento -> True
Correo_Electronico -> True
No_DireccionEfectiva -> True
Regional -> True
INDICADOR -> True
DIRECTOR_REGIONAL -> True
Modo_de_envío -> True
numero_expediente -> True
Acto_Administrativo_No_y_fecha -> True
Nombre_Notificado -> True
Tipo_de_documento -> True
Funcionario_que_expide -> True
Recurso_actoadministrativo -> True

,Numero_Documento,Correo_Electronico,No_DireccionEfectiva,Regional,INDICADOR,DIRECTOR_REGIONAL,Modo_de_envío,numero_expediente,Acto_Administrativo_No_y_fecha,Nombre_Notificado,Tipo_de_documento,Funcionario_que_expide,Recurso_actoadministrativo
0,899.999.071-0,giovannipadillatellez@gmail.com,CARRERA 10 N°16-82 PISO 8 Bogotá,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,FÍSICO,40381,Resolución DRBC No. 01237000397 de 28 dicie...,"PROCURADURIA 22 JUDICIAL II, AMBIENTAL Y AGRARIA""",NIT,MARÍA FERNANDA ZULUAGA MARTÍNEZ,No Aplica
1,3079328,NaN,CALLE 10 N° 3- 30 LA HOYITA CAPARRAPI,Bajo Magdalena,DRBM,JUAN FILIBERTO COTRINO GUEVARA,FÍSICO,45586,Resolución No. 1387 de 31 de mayo de 2017,ALIRIO VANEGAS,Cédula de ciudadania,JUAN CAMILO FERŘER TOBÓN,Reposición
2,11.228.476,manuel_carvajal04@hotmail.com,Calle 3 No 23 B - 23 Barrio La Esperanza,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,ELECTRÓNICO,44696,RESOLUCIÓN DJUR No. 50257000463 del 11 de juli...,MANUEL DAVID CARVAJAL BERMUDEZ,Cédula de ciudadania,EMMA CONSTANZA ZUÑIGA GALVIS,Recurso de reposición

In [248]:
print("VALORES ÚNICOS DE ACTUACION:\n")
print(sorted(df_words["ACTUACION"].astype(str).str.strip().unique().tolist()))

VALORES ÚNICOS DE ACTUACION:

['AVISO', 'CITACION', 'COMUNICACION', 'EDICTO', 'EN CONSULTA DR', 'EN OTRO ESTADO SAE', 'NOTIFICACIÓN ELECTRÓNICA', 'PARA EJECUTORIA', 'PUBLICAR AVISO', 'PUBLICAR CITACION']

# PASO FINAL

In [249]:
from docx import Document
from pathlib import Path
import pandas as pd

ruta_plantillas = Path("plantillas")

def extraer_texto_docx(ruta_docx):
    doc = Document(str(ruta_docx))
    partes = []

    for p in doc.paragraphs:
        if p.text.strip():
            partes.append(p.text.strip())

    for t in doc.tables:
        for row in t.rows:
            for cell in row.cells:
                for p in cell.paragraphs:
                    if p.text.strip():
                        partes.append(p.text.strip())

    return "\n".join(partes)

registros = []

for archivo in ruta_plantillas.glob("*.docx"):
    texto = extraer_texto_docx(archivo)

    tiene_marcadores = any(x in texto for x in ["«", ">>", "{{", "["])
    tiene_datos_quemados = any(x in texto for x in [
        "40381",
        "41480",
        "01237000397",
        "50237000469",
        "giovannipadillatellez@gmail.com",
        "comunicacionespgn@procuraduria.gov.co",
        "YUBER YESID CARDENAS PULIDO",
        "PROCURADORIA JUDICIAL"
    ])

    registros.append({
        "archivo": archivo.name,
        "tiene_marcadores": tiene_marcadores,
        "tiene_datos_quemados": tiene_datos_quemados,
        "muestra_texto": texto[:300]
    })

df_revision_plantillas = pd.DataFrame(registros)
display(df_revision_plantillas)

,archivo,tiene_marcadores,tiene_datos_quemados,muestra_texto
0,Formato Aviso Recurso (AUTOMATIZADO).docx,True,False,DATOS DE ENVIO\n# IDENTIFICACION NOTIFICADO «N...
1,Formato Citación CPACA2011 (Automatizado).docx,True,False,DATOS DE ENVIO\n# IDENTIFICACION NOTIFICADO «N...
2,Formato Comunicación (Automatizado).docx,True,False,DATOS DE ENVIO\n# IDENTIFICACION NOTIFICADO «N...
3,Notificación electrónica (Automatizado).docx,True,False,DATOS DE ENVIO :\n# IDENTIFICACION NOTIFICADO:...

In [250]:
import shutil
from pathlib import Path
from utils import Utils

utils = Utils()

# Limpiar salida final
ruta_final = Path("output_abogados")
if ruta_final.exists():
    shutil.rmtree(ruta_final)

# Base final solo para oficios válidos
COL_ESTADO = "Estado de la Actuacion"
COL_ACTUACION = "ACTUACION"

df_oficios = df_filtrado.copy()

df_oficios = df_oficios[
    df_oficios[COL_ESTADO].astype(str).str.strip().str.lower().eq("elaborar oficio")
].copy()

no_validos = ["EJECUTORIA", "EDICTO", "EN CONSULTA DR"]
mask_no_validos = df_oficios[COL_ACTUACION].astype(str).str.upper().apply(
    lambda x: any(p in x for p in no_validos)
)
df_oficios = df_oficios[~mask_no_validos].copy()

df_oficios = utils.agregar_info_regional(df_oficios, col_regional="Regional")

df_oficios["Numero_Documento"] = df_oficios["Numero Documento"]
df_oficios["Correo_Electronico"] = df_oficios["Correo Electronico"]
df_oficios["No_DireccionEfectiva"] = df_oficios["No. DireccionEfectiva"]
df_oficios["Tipo_de_documento"] = df_oficios["Tipo de documento"]
df_oficios["Funcionario_que_expide"] = df_oficios["Funcionario que expide"]
df_oficios["Nombre_Notificado"] = df_oficios["Nombre Notificado"]

def construir_modo_envio(row):
    actuacion = str(row.get("ACTUACION", "")).strip().upper()
    autoriza = str(row.get("Autoriza Notificacion electrónica", "")).strip().lower()
    correo = str(row.get("Correo Electronico", "")).strip()

    if "NOTIFICACIÓN ELECTRÓNICA" in actuacion or "NOTIFICACION ELECTRONICA" in actuacion:
        return "ELECTRÓNICO"
    if autoriza in ["si", "sí", "s", "true", "1", "x"] and correo != "":
        return "ELECTRÓNICO"
    return "FÍSICO"

df_oficios["Modo_de_envío"] = df_oficios.apply(construir_modo_envio, axis=1)
df_oficios["Modo_de_envio"] = df_oficios["Modo_de_envío"]

def homologar_actuacion(x):
    txt = str(x).strip().upper()
    if "AVISO" in txt:
        return "AVISO"
    if "CITACION" in txt:
        return "CITACION"
    if "COMUNICACION" in txt:
        return "COMUNICACION"
    if "NOTIFICACIÓN ELECTRÓNICA" in txt or "NOTIFICACION ELECTRONICA" in txt:
        return "NOTIFICACIÓN ELECTRÓNICA"
    return txt

df_oficios["ACTUACION_NORMALIZADA"] = df_oficios["ACTUACION"].apply(homologar_actuacion)

resumen_final = utils.generar_words_desde_tipo_oficio(
    df=df_oficios,
    carpeta_salida="output_abogados",
    col_notificador="Notificador/Revisor",
    col_estado_actuacion="Estado de la Actuacion",
    col_tipo_oficio="ACTUACION_NORMALIZADA",
    col_subcarpeta=None,
    nombre_archivo_cols=["numero_expediente", "Nombre_Notificado"],
    col_map={}
)

display(resumen_final.head(20))
print("Total generados:", len(resumen_final))

if "error" in resumen_final.columns:
    errores = resumen_final[resumen_final["error"].notna()]
    print("Total errores:", len(errores))
    if len(errores) > 0:
        display(errores.head(50))

,fila,abogado,tipo_oficio,plantilla,ruta_docx,archivo,error
0,0,Diana Carolina Morera Acuña,comunicacion,Formato Comunicación (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,"OFICIO_40381_PROCURADURIA_22_JUDICIAL_II,_AMBI...",NaN
1,1,Laura Stephania Martinez Leandro,aviso,Formato Aviso Recurso (AUTOMATIZADO).docx,output_abogados\Laura_Stephania_Martinez_Leand...,OFICIO_53016_MARTHA_DE_LA_CONCEPCION_GOMEZ_CAS...,NaN
2,2,Laura Stephania Martinez Leandro,aviso,Formato Aviso Recurso (AUTOMATIZADO).docx,output_abogados\Laura_Stephania_Martinez_Leand...,OFICIO_74305_FERNANDO_REY_MORENO.docx,NaN
3,3,Diana Carolina Morera Acuña,citacion,Formato Citación CPACA2011 (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_40388_HECTOR_JAIRO_SARMIENTO_GOMEZ.docx,NaN
4,4,Diana Carolina Morera Acuña,citacion,Formato Citación CPACA2011 (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_40388_GABRIEL_ESTRADA.docx,NaN
5,5,Diana Carolina Morera Acuña,aviso,Formato Aviso Recurso (AUTOMATIZADO).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_40388_ESTRAURI_S.A.S.docx,NaN
6,6,Diana Carolina Morera Acuña,aviso,Formato Aviso Recurso (AUTOMATIZADO).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41480_ANDRES_BARRAGAN_TOBAR.docx,NaN
7,7,Diana Carolina Morera Acuña,comunicacion,Formato Comunicación (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41480_PROCURADORIA_JUDICIAL_AMBIENTAL_Y...,NaN
8,8,Diana Carolina Morera Acuña,citacion,Formato Citación CPACA2011 (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41564_RAUL_CASTELLANOS.docx,NaN
9,9,Diana Carolina Morera Acuña,citacion,Formato Citación CPACA2011 (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41564_CARLOS_MUÑOZ_ROJAS.docx,NaN
10,10,Diana Carolina Morera Acuña,aviso,Formato Aviso Recurso (AUTOMATIZADO).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41570_EMILIO_BELTRÁN.docx,NaN
11,11,Diana Carolina Morera Acuña,citacion,Formato Citación CPACA2011 (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41874_JOSÉ_IGNACIO_PRECIADO_GARCÍA.docx,NaN
12,12,Diana Carolina Morera Acuña,citacion,Formato Citación CPACA2011 (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41874_CARLOS_ARTURO_PRECIADO_GARCÍA.docx,NaN
13,13,Diana Carolina Morera Acuña,citacion,Formato Citación CPACA2011 (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41874_BLANCA_MARÍA_BAZZANI_DE_AYALA.docx,NaN
14,14,Diana Carolina Morera Acuña,comunicacion,Formato Comunicación (Automatizado).docx,output_abogados\Diana_Carolina_Morera_Acuña\WO...,OFICIO_41874_PROCURADORIA_JUDICIAL_AMBIENTAL_Y...,NaN
15,15,Ana Maria Guzman Acosta,comunicacion,Formato Comunicación (Automatizado).docx,output_abogados\Ana_Maria_Guzman_Acosta\WORDS\...,"OFICIO_53586_PROCURADURIA_22_JUDICIAL_II,_AMBI...",NaN
16,16,Ana Maria Guzman Acosta,aviso,Formato Aviso Recurso (AUTOMATIZADO).docx,output_abogados\Ana_Maria_Guzman_Acosta\WORDS\...,OFICIO_54346_PRODECA_S.A.docx,NaN
17,17,Laura Stephania Martinez Leandro,comunicacion,Formato Comunicación (Automatizado).docx,output_abogados\Laura_Stephania_Martinez_Leand...,OFICIO_83445_EMILSE_SERNA_BASTOS.docx,NaN
18,18,Laura Stephania Martinez Leandro,aviso,Formato Aviso Recurso (AUTOMATIZADO).docx,output_abogados\Laura_Stephania_Martinez_Leand...,OFICIO_89438_MICHAEL_STEVENTS_BELTRAN_MARIN.docx,NaN
19,19,Ana Maria Guzman Acosta,comunicacion,Formato Comunicación (Automatizado).docx,output_abogados\Ana_Maria_Guzman_Acosta\WORDS\...,OFICIO_65453_PROCURADURIA_JUDICIAL.docx,NaN

Total generados: 122
Total errores: 2

,fila,abogado,tipo_oficio,plantilla,ruta_docx,archivo,error
37,37,Ana Maria Guzman Acosta,en otro estado sae,NaN,NaN,NaN,Tipo no válido para generar entregable: EN OTR...
74,74,Ana Maria Guzman Acosta,en otro estado sae,NaN,NaN,NaN,Tipo no válido para generar entregable: EN OTR...