Entrada

In [9]:
from loaders import Loaders
from utils import Utils
ld= Loaders()
utils= Utils()

In [10]:

# 01 - Cargar y visualizar base (Basenotificar.xlsx)

from loaders import Loaders
ld = Loaders()
path_archivo = r"input/Basenotificar.xlsx"  # <-- cambia si tu ruta es distinta
nombre_hoja = "query"                       # <-- tu hoja se llama "query"
df = ld.cargar_excel(path_archivo, nombre_hoja)

if df is None:
    raise FileNotFoundError(
        "No se pudo cargar el Excel. Revisa:\n"
        f"- Ruta: {path_archivo}\n"
        f"- Hoja: {nombre_hoja}\n"
        "Si el archivo expiró en el chat, vuelve a subirlo o cópialo a ./input/"
    )


print("✅ Base cargada correctamente")
print("Shape (filas, columnas):", df.shape)
print("\nColumnas:")
print(df.columns.tolist())

display(df.head(10))
display(df.info())

# Nulos por columna (top 30 para no saturar)
nulos = df.isna().sum().sort_values(ascending=False)
display(nulos.head(30))

✅ Base cargada correctamente
Shape (filas, columnas): (60, 23)

Columnas:
['Notificador/Revisor', 'numero_expediente', 'Regional', 'Estado de la Actuacion', 'ACTUACION', 'Norma Aplicable', 'Permisivo/Sancionatorio', 'Recurso', 'Acto_Administrativo_No_y_fecha', 'Recurso_actoadministrativo', 'Ordena', 'Tipo de Acto Administrativo', 'Funcionario que expide', 'Nombre Notificado', 'Tipo de documento', 'Numero Documento', 'No. DireccionEfectiva', 'Autoriza Notificacion electrónica', 'Correo Electronico', 'Radicado de autorización Electronica', 'Modo de envío', 'Tipo de elemento', 'Ruta de acceso']

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Nombre Notificado,Tipo de documento,Numero Documento,No. DireccionEfectiva,Autoriza Notificacion electrónica,Correo Electronico,Radicado de autorización Electronica,Modo de envío,Tipo de elemento,Ruta de acceso
0,Ana Maria Guzman Acosta,39618,Bajo Magdalena,Enviado,EN OTRO ESTADO SAE,Ley 1437,Sancionatorio,Recurso,Resolucion DJA No. 50257000923 del 29 Octubr...,Reposicion,...,CARLOS ALBERTO SÁNCHEZ BARÓN,Cédula de ciudadania,19388990,Diagonal 87C No.82-46,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
1,Ana Maria Guzman Acosta,39618,Bajo Magdalena,Enviado,EN OTRO ESTADO SAE,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN No. 50257000923 del 29 de octubre ...,Reposicion,...,SADIN JESUS JIMENEZ HERNÁNDEZ,Cédula de ciudadania,10176897,CALLE 34 No.52-10 Naranjales Medellín (Antioquia),False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
2,Ana Maria Guzman Acosta,39618,Bajo Magdalena,Enviado,EN OTRO ESTADO SAE,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN No. 50257000923 del 29 de octubre ...,Reposicion,...,JOSE DONARDO URIBE GÓMEZ,Cédula de ciudadania,8038334,Calle 1 No. 4-04,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
3,Ana Maria Guzman Acosta,41735,Bajo Magdalena,En consulta de la Regional,EN CONSULTA DR,Ley 1437,Sancionatorio,Recurso,Resolución N°4705 Del 31 de Diciembre de 2018,Reposicion,...,MUNICIPIO DE PUERTO SALGAR,NIT,8999994138,Transversal 11A Calle 11 # 25-27,True,alcaldia@puertosalgar-cundinamarca.gov.co,4.191101e+09,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
4,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,"PROCURADURIA 22 JUDICIAL II, AMBIENTAL Y AGRARIA""",NIT,899.999.071-0,CARRERA 10 N°16-82 PISO 8 Bogotá,False,giovannipadillatellez@gmail.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
5,Andrea Claudia Martin Martinez,81918,Soacha,Elaborar Oficio,NOTIFICACIÓN ELECTRÓNICA,Ley 1437,Sancionatorio,No recurso,Resolución DJA No. 50267000060 del 17 de febre...,No Aplica,...,CONJUNTO RESIDENCIAL PORTAL DE CASALINDA PROPI...,NIT,832.004.399-1,Calle 30 No. 1 - 165,True,portcasalinda@yahoo.es,1.124100e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
6,Andrea Claudia Martin Martinez,73233,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DJUR No. 50257000727 del 23 de sept...,No aplica,...,PROCURADURIA DELEGADA PARA ASUNTOS AMBIENTALES...,NIT,899.999.119-7,Cra 5 No. 15 - 60,True,procesosjudiciales@procuraduria.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
7,Andrea Claudia Martin Martinez,93441,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Permisivo,Recurso,Resolución DRSOA No. 11257000090 del 02 de dic...,Reposición,...,ALCALDIA MUNICIPAL DE SOACHA,NIT,800.094.755-7,Calle 13 Nº 7-30 Soacha,True,contactenos@alcaldiasoacha.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
8,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,"FLOR GRISELDA PINTO ZABALA,",Cédula de ciudadania,20632169,Predio las delicias vereda Perú Guaduas,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
9,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,"LUIS FERNANDO RODRÍGUEZ ZABALA,",Cédula de ciudadania,79003599,Predio Cajon Vereda Raizal Guaduas,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Notificador/Revisor                   60 non-null     str
 1   numero_expediente                     60 non-null     int64
 2   Regional                              60 non-null     str
 3   Estado de la Actuacion                60 non-null     str
 4   ACTUACION                             60 non-null     str
 5   Norma Aplicable                       60 non-null     str
 6   Permisivo/Sancionatorio               60 non-null     str
 7   Recurso                               60 non-null     str
 8   Acto_Administrativo_No_y_fecha        60 non-null     str
 9   Recurso_actoadministrativo            59 non-null     str
 10  Ordena                                60 non-null     str
 11  Tipo de Acto Administrativo           60 non-null     str
 12  Funcionario que expide                60 non-null     str
 13  Nombre Notificado                     60 non-null     str
 14  Tipo de documento                     60 non-null     str
 15  Numero Documento                      60 non-null     str
 16  No. DireccionEfectiva                 60 non-null     str
 17  Autoriza Notificacion electrónica     60 non-null     bool
 18  Correo Electronico                    25 non-null     str
 19  Radicado de autorización Electronica  12 non-null     float64
 20  Modo de envío                         60 non-null     str
 21  Tipo de elemento                      60 non-null     str
 22  Ruta de acceso                        60 non-null     str
dtypes: bool(1), float64(1), int64(1), str(20)
memory usage: 10.5 KB

None

Radicado de autorización Electronica    48
Correo Electronico                      35
Recurso_actoadministrativo               1
Estado de la Actuacion                   0
Notificador/Revisor                      0
numero_expediente                        0
Regional                                 0
Permisivo/Sancionatorio                  0
Norma Aplicable                          0
ACTUACION                                0
Recurso                                  0
Tipo de Acto Administrativo              0
Funcionario que expide                   0
Acto_Administrativo_No_y_fecha           0
Ordena                                   0
Tipo de documento                        0
Nombre Notificado                        0
No. DireccionEfectiva                    0
Numero Documento                         0
Autoriza Notificacion electrónica        0
Modo de envío                            0
Tipo de elemento                         0
Ruta de acceso                           0
dtype: int64

Segmentos de elaborar oficios

In [11]:
# ============================================================
# 02 - Filtrar SOLO los registros con "Elaborar Oficio"
#      (columna correcta: "Estado de la Actuacion")
# ============================================================

import unicodedata

def _norm_txt(x: str) -> str:
    x = "" if x is None else str(x)
    x = x.strip().upper()
    x = " ".join(x.split())
    x = unicodedata.normalize("NFKD", x).encode("ascii", "ignore").decode("ascii")
    return x

col_estado_act = "Estado de la Actuacion"
valor_objetivo = "Elaborar Oficio"


if col_estado_act not in df.columns:
    # Si por algún motivo viene con otra escritura, mostramos candidatas
    candidatas = [c for c in df.columns if "estado" in _norm_txt(c) and "actu" in _norm_txt(c)]
    raise KeyError(
        f"No existe la columna '{col_estado_act}'.\n"
        f"Candidatas encontradas: {candidatas}\n"
        f"Columnas disponibles: {df.columns.tolist()}"
    )

tmp = df.copy()
tmp["_estado_norm"] = tmp[col_estado_act].map(_norm_txt)

df_filtrado = tmp[tmp["_estado_norm"] == _norm_txt(valor_objetivo)].drop(columns=["_estado_norm"]).copy()
df_filtrado.reset_index(drop=True, inplace=True)

print("✅ Filtrado aplicado por Estado de la Actuacion == 'Elaborar Oficio'")
print("Shape original:", df.shape)
print("Shape filtrado :", df_filtrado.shape)

display(df_filtrado.head(10))
display(df[col_estado_act].astype(str).value_counts(dropna=False).head(20))

✅ Filtrado aplicado por Estado de la Actuacion == 'Elaborar Oficio'
Shape original: (60, 23)
Shape filtrado : (48, 23)

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Nombre Notificado,Tipo de documento,Numero Documento,No. DireccionEfectiva,Autoriza Notificacion electrónica,Correo Electronico,Radicado de autorización Electronica,Modo de envío,Tipo de elemento,Ruta de acceso
0,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,"PROCURADURIA 22 JUDICIAL II, AMBIENTAL Y AGRARIA""",NIT,899.999.071-0,CARRERA 10 N°16-82 PISO 8 Bogotá,False,giovannipadillatellez@gmail.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
1,Andrea Claudia Martin Martinez,81918,Soacha,Elaborar Oficio,NOTIFICACIÓN ELECTRÓNICA,Ley 1437,Sancionatorio,No recurso,Resolución DJA No. 50267000060 del 17 de febre...,No Aplica,...,CONJUNTO RESIDENCIAL PORTAL DE CASALINDA PROPI...,NIT,832.004.399-1,Calle 30 No. 1 - 165,True,portcasalinda@yahoo.es,1.124100e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
2,Andrea Claudia Martin Martinez,73233,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DJUR No. 50257000727 del 23 de sept...,No aplica,...,PROCURADURIA DELEGADA PARA ASUNTOS AMBIENTALES...,NIT,899.999.119-7,Cra 5 No. 15 - 60,True,procesosjudiciales@procuraduria.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
3,Andrea Claudia Martin Martinez,93441,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Permisivo,Recurso,Resolución DRSOA No. 11257000090 del 02 de dic...,Reposición,...,ALCALDIA MUNICIPAL DE SOACHA,NIT,800.094.755-7,Calle 13 Nº 7-30 Soacha,True,contactenos@alcaldiasoacha.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
4,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,"FLOR GRISELDA PINTO ZABALA,",Cédula de ciudadania,20632169,Predio las delicias vereda Perú Guaduas,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
5,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,"LUIS FERNANDO RODRÍGUEZ ZABALA,",Cédula de ciudadania,79003599,Predio Cajon Vereda Raizal Guaduas,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
6,Ana Maria Garcia Rodriguez,45586,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución No. 1387 de 31 de mayo de 2017,Reposición,...,ALIRIO VANEGAS,Cédula de ciudadania,3079328,CALLE 10 N° 3- 30 LA HOYITA CAPARRAPI,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
7,Ana Maria Guzman Acosta,49743,Bajo Magdalena,Elaborar Oficio,EN CONSULTA DR,Ley 1437,Sancionatorio,Recurso,Resolución No. 4741 del 31 de diciembre de 2018,Reposición,...,ESTACIÓN DE SERVICIO TERPEL MONTECRISTO,NIT,83009521301,Carrera 7 No. 75 - 51 Bogota,True,viviana.rodas@terpel.com,2.020114e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
8,Laura Stephania Martinez Leandro,44696,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000463 del 11 de juli...,Recurso de reposición,...,MANUEL DAVID CARVAJAL BERMUDEZ,Cédula de ciudadania,11.228.476,Calle 3 No 23 B - 23 Barrio La Esperanza,True,manuel_carvajal04@hotmail.com,3.246002e+09,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes
9,Laura Stephania Martinez Leandro,53016,Alto Magdalena,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000556 del 21 de agos...,recurso de reposición,...,MARTHA DE LA CONCEPCION GOMEZ CASTRO,Cédula de ciudadania,39550755,HC LA CONCEPCION KM 9 VIA GIRARDOT VEREDA GUAB...,False,yedanisel@gmail.com,NaN,Direccion desconocida,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes

Estado de la Actuacion
Elaborar Oficio               48
Enviado                        6
En consulta de la Regional     6
Name: count, dtype: int64

Agregamos Regionales con nombre de director e indicador

In [12]:


df_filtrado = utils.agregar_info_regional(df_filtrado, col_regional="Regional")

print("✅ Columnas agregadas:", ["INDICADOR", "DIRECTOR_REGIONAL"])
display(df_filtrado[["Regional", "INDICADOR", "DIRECTOR_REGIONAL"]].head(15))

✅ Columnas agregadas: ['INDICADOR', 'DIRECTOR_REGIONAL']

            Regional INDICADOR                DIRECTOR_REGIONAL
0   Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
1             Soacha     DRSOA       CESAR AUGUSTO RICO MAYORGA
2             Soacha     DRSOA       CESAR AUGUSTO RICO MAYORGA
3             Soacha     DRSOA       CESAR AUGUSTO RICO MAYORGA
4     Bajo Magdalena      DRBM   JUAN FILIBERTO COTRINO GUEVARA
5     Bajo Magdalena      DRBM   JUAN FILIBERTO COTRINO GUEVARA
6     Bajo Magdalena      DRBM   JUAN FILIBERTO COTRINO GUEVARA
7     Bajo Magdalena      DRBM   JUAN FILIBERTO COTRINO GUEVARA
8     Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
9     Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
10    Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
11    Alto Magdalena      DRAM  CAMILA ANDREA VELASQUEZ BAQUERO
12  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
13  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO
14  Bogota la Calera      DRBC      YUBER YESID CARDENAS PULIDO

In [13]:
df_filtrado

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Autoriza Notificacion electrónica,Correo Electronico,Radicado de autorización Electronica,Modo de envío,Tipo de elemento,Ruta de acceso,INDICADOR,DIRECTOR_REGIONAL,DIRECCION_REGIONAL,MUNICIPIO_REGIONAL
0,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,False,giovannipadillatellez@gmail.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
1,Andrea Claudia Martin Martinez,81918,Soacha,Elaborar Oficio,NOTIFICACIÓN ELECTRÓNICA,Ley 1437,Sancionatorio,No recurso,Resolución DJA No. 50267000060 del 17 de febre...,No Aplica,...,True,portcasalinda@yahoo.es,1.124100e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
2,Andrea Claudia Martin Martinez,73233,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DJUR No. 50257000727 del 23 de sept...,No aplica,...,True,procesosjudiciales@procuraduria.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
3,Andrea Claudia Martin Martinez,93441,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Permisivo,Recurso,Resolución DRSOA No. 11257000090 del 02 de dic...,Reposición,...,True,contactenos@alcaldiasoacha.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
4,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
5,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
6,Ana Maria Garcia Rodriguez,45586,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución No. 1387 de 31 de mayo de 2017,Reposición,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
7,Ana Maria Guzman Acosta,49743,Bajo Magdalena,Elaborar Oficio,EN CONSULTA DR,Ley 1437,Sancionatorio,Recurso,Resolución No. 4741 del 31 de diciembre de 2018,Reposición,...,True,viviana.rodas@terpel.com,2.020114e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
8,Laura Stephania Martinez Leandro,44696,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000463 del 11 de juli...,Recurso de reposición,...,True,manuel_carvajal04@hotmail.com,3.246002e+09,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
9,Laura Stephania Martinez Leandro,53016,Alto Magdalena,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50257000556 del 21 de agos...,recurso de reposición,...,False,yedanisel@gmail.com,NaN,Direccion desconocida,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
10,Laura Stephania Martinez Leandro,57314,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DRAM No. 03257000146 del 24 de sept...,recurso de reposición,...,True,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
11,Laura Stephania Martinez Leandro,74305,Alto Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJA No. 50257001140 del 24 de dicie...,recurso de reposición,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
12,Diana Carolina Morera Acuña,40388,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolución DRBC No. 01237000081 de 31 marzo...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
13,Diana Carolina Morera Acuña,40388,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolucion DRBC No. 01237000081 de 31 marzo...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
14,Diana Carolina Morera Acuña,40388,Bogota la Calera,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolucion DRBC No. 01237000081 de 31 marzo...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
15,Diana Carolina Morera Acuña,41480,Bogota la Calera,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50237000469 de 31 MAR. ...,Reposicion,...,False,mcpachonv@compensarsalud.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
16,Diana Carolina Morera Acuña,41480,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237000469 de 31 marzo...,reposicion,...,False,comunicacionespgn@procuraduria.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
17,Diana Carolina Morera Acuña,41564,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJUR No. 50237000472 de 31 MAR. ...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
18,Andrea Claudia Martin Martinez,69585,Soacha,Elaborar Oficio,NOTIFICACIÓN ELECTRÓNICA,Ley 1437,Sancionatorio,Recurso,Resolución DJA No. 50257000963 del 10 de novie...,Reposición,...,True,rodriguezcruzangelsneyder@gmail.com,2.320000e+02,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
19,Diana Carolina Morera Acuña,41564,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237000472 de 31 marzo...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
20,Diana Carolina Morera Acuña,41564,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237000472 de 31 marzo...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
21,Diana Carolina Morera Acuña,41570,Bogota la Calera,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237002990 de 28 dicie...,Resposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
22,Diana Carolina Morera Acuña,41874,Bogota la Calera,Elaborar Oficio,EDICTO,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237003006 de 29 dicie...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
23,Diana Carolina Morera Acuña,41874,Bogota la Calera,Elaborar Oficio,PUBLICAR CITACION,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237003006 de 29 dicie...,Reposicion,...,False,ANGELICA_PRECIADO@HOTMAIL.ES,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
24,Diana Carolina Morera Acuña,41874,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237003006 de 29 dicie...,Reposicion,...,False,carlosapreciado2009@gmail.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
25,Diana Carolina Morera Acuña,41874,Bogota la Calera,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237003006 de 29 dicie...,Resposicion,...,False,camargo737@gmail.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
26,Diana Carolina Morera Acuña,41874,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,Recurso,Resolucion DJUR No. 50237003006 de 29 dicie...,Reposicion,...,False,comunicacionespgn@procuraduria.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
27,Andrea Claudia Martin Martinez,69585,Soacha,Elaborar Oficio,CITACION,Ley 1437,Sancionatorio,Recurso,Resolución DJA No. 50257000963 del 10 de novie...,Reposición,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
28,Andrea Claudia Martin Martinez,78981,Soacha,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50257000729 del 25 de sept...,Reposición,...,False,alveiroburbano@hotmail.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
29,Ana Maria Guzman Acosta,53586,Bajo Magdalena,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50257000611 del 25 Agosto...,Reposicion,...,False,giovannipadillatellez@gmail.com,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
30,Andrea Claudia Martin Martinez,44874,Soacha,Elaborar Oficio,NOTIFICACIÓN ELECTRÓNICA,CCA,Sancionatorio,Recurso,Resolución DJUR No. 50257000693 del 15 de sept...,Reposición,...,True,notijudicial_bene@cundinamarca.gov.co,2.020114e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
31,Andrea Claudia Martin Martinez,44874,Soacha,Elaborar Oficio,NOTIFICACIÓN ELECTRÓNICA,CCA,Sancionatorio,Recurso,Resolución DJUR No. 50257000693 del 15 de sept...,Reposición,...,True,mauriciolmj1712@gmail.com,1.060000e+02,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
32,Ana Maria Guzman Acosta,54346,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50257000839 del 21 octubre...,Reposicion,...,True,psanchez@prodeca.com.co,2.024113e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
33,Laura Stephania Martinez Leandro,83445,Alto Magdalena,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJA No. 50257000926 del 29 de octub...,recurso de reposición,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
34,Laura Stephania Martinez Leandro,89106,Alto Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DRAM No. 03257000046 del 18 de marz...,recurso de reposición,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
35,Laura Stephania Martinez Leandro,89438,Alto Magdalena,Elaborar Oficio,PUBLICAR AVISO,Ley 1437,Sancionatorio,Recurso,RESOLUCIÓN DJA No. 50257001135 del 23 de dicie...,recurso de reposición,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
36,Ana Maria Guzman Acosta,54765,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50227002078 del 21 de dici...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
37,Ana Maria Guzman Acosta,56766,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1333,Sancionatorio,Recurso,Resolución DJUR No. 50247000665 del 24 Dicie...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
38,Ana Maria Guzman Acosta,60182,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1333,Sancionatorio,Recurso,Resolución DJUR No. 50257000785 del 9 de Oct...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
39,Ana Maria Guzman Acosta,62944,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50257000828 del 21 Octubr...,Reposicion,...,False,juridico@guaduas-cundinamarca.gov.co,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
40,Ana Maria Guzman Acosta,65453,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50237001079 del 22 de juni...,Reosicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
41,Ana Maria Guzman Acosta,65453,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50237001079 del 22 de juni...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
42,Ana Maria Guzman Acosta,65453,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50237001079 del 22 de juni...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
43,Ana Maria Guzman Acosta,65453,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50237001079 del 22 de juni...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
44,Ana Maria Guzman Acosta,65453,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50237001079 del 22 de juni...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
45,Ana Maria Guzman Acosta,65453,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50237001079 del 22 de juni...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
46,Ana Maria Guzman Acosta,65453,Bajo Magdalena,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50237001079 del 22 junio d...,Reposicion,...,True,NaN,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
47,Ana Maria Guzman Acosta,65467,Bajo Magdalena,Elaborar Oficio,PARA EJECUTORIA,Ley 1437,Sancionatorio,Recurso,Resolución DJA No. 50257000935 del 31 de O...,Reposicion,...,True,inversionesgamburibe@outlook.es,2.024112e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"

Direcciones de cada regional

In [14]:


df_filtrado = utils.agregar_info_regional(df_filtrado, col_regional="Regional")

display(
    df_filtrado[["Regional", "INDICADOR", "DIRECTOR_REGIONAL", "DIRECCION_REGIONAL", "MUNICIPIO_REGIONAL"]]
    .head(15)
)

,Regional,INDICADOR,DIRECTOR_REGIONAL,DIRECCION_REGIONAL,MUNICIPIO_REGIONAL
0,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
1,Soacha,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
2,Soacha,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
3,Soacha,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
4,Bajo Magdalena,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
5,Bajo Magdalena,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
6,Bajo Magdalena,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
7,Bajo Magdalena,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"
8,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
9,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
10,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
11,Alto Magdalena,DRAM,CAMILA ANDREA VELASQUEZ BAQUERO,Calle 21 No. 8 – 23 Barrio Granada,"Girardot, Cundinamarca"
12,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
13,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
14,Bogota la Calera,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"

Validacion de dataframe en asignaciones

In [15]:
print("📌 RESUMEN GENERAL")
print("="*50)
print("Filas:", df_filtrado.shape[0])
print("Columnas:", df_filtrado.shape[1])
print("="*50)

display(df_filtrado.head(5))

📌 RESUMEN GENERAL
==================================================
Filas: 48
Columnas: 27
==================================================

,Notificador/Revisor,numero_expediente,Regional,Estado de la Actuacion,ACTUACION,Norma Aplicable,Permisivo/Sancionatorio,Recurso,Acto_Administrativo_No_y_fecha,Recurso_actoadministrativo,...,Autoriza Notificacion electrónica,Correo Electronico,Radicado de autorización Electronica,Modo de envío,Tipo de elemento,Ruta de acceso,INDICADOR,DIRECTOR_REGIONAL,DIRECCION_REGIONAL,MUNICIPIO_REGIONAL
0,Diana Carolina Morera Acuña,40381,Bogota la Calera,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DRBC No. 01237000397 de 28 dicie...,No Aplica,...,False,giovannipadillatellez@gmail.com,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBC,YUBER YESID CARDENAS PULIDO,Carrera 10 N° 16-82 piso 4,"Bogotá, Cundinamarca"
1,Andrea Claudia Martin Martinez,81918,Soacha,Elaborar Oficio,NOTIFICACIÓN ELECTRÓNICA,Ley 1437,Sancionatorio,No recurso,Resolución DJA No. 50267000060 del 17 de febre...,No Aplica,...,True,portcasalinda@yahoo.es,1.124100e+10,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
2,Andrea Claudia Martin Martinez,73233,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Sancionatorio,No recurso,Resolución DJUR No. 50257000727 del 23 de sept...,No aplica,...,True,procesosjudiciales@procuraduria.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
3,Andrea Claudia Martin Martinez,93441,Soacha,Elaborar Oficio,COMUNICACION,Ley 1437,Permisivo,Recurso,Resolución DRSOA No. 11257000090 del 02 de dic...,Reposición,...,True,contactenos@alcaldiasoacha.gov.co,NaN,Direccion electronica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRSOA,CESAR AUGUSTO RICO MAYORGA,Trans. 7 F N° 26-38 Barrio El Nogal - Soacha,"Soacha, Cundinamarca"
4,Ana Maria Guzman Acosta,44168,Bajo Magdalena,Elaborar Oficio,AVISO,Ley 1437,Sancionatorio,Recurso,Resolución DJUR No. 50247000474 del 7 noviembr...,Reposicion,...,False,NaN,NaN,Direccion fisica,Elemento,sites/NOTIFICACIONES2026/Lists/expedientes,DRBM,JUAN FILIBERTO COTRINO GUEVARA,Calle 4 N° 5-68 Camellón Real,"Guaduas, Cundinamarca"

DataFrame con abogados independientes

In [17]:
import importlib
import utils as utils_module
importlib.reload(utils_module)

from utils import Utils
utils = Utils()

print("✅ utils recargado. Métodos disponibles (filtrado):")
print([m for m in dir(utils) if "persona" in m or "cruce" in m])

✅ utils recargado. Métodos disponibles (filtrado):
['agregar_fila_cruce', 'agregar_fila_cruce_excel', 'agregar_fila_cruce_word', 'exportar_excels_por_persona', 'partir_por_persona_con_cruce']

Exportar excel abogado

In [18]:


resumen = utils.exportar_excels_por_persona(
    df=df_filtrado,
    col_persona="Notificador/Revisor",
    carpeta_salida="output_abogados",
    nombre_prefix="OFICIOS",
    add_fila_cruce=True,
    col_fila_cruce="No_Fila_Cruce",
    offset_fila_cruce=3
)

display(resumen)

,persona,filas,ruta_archivo
0,Ana Maria Garcia Rodriguez,1,output_abogados\OFICIOS_Ana_Maria_Garcia_Rodri...
1,Ana Maria Guzman Acosta,17,output_abogados\OFICIOS_Ana_Maria_Guzman_Acost...
2,Andrea Claudia Martin Martinez,8,output_abogados\OFICIOS_Andrea_Claudia_Martin_...
3,Diana Carolina Morera Acuña,15,output_abogados\OFICIOS_Diana_Carolina_Morera_...
4,Laura Stephania Martinez Leandro,7,output_abogados\OFICIOS_Laura_Stephania_Martin...